import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from 'next/font/google'
import NavBar from "@/components/NavBar";
import MobileNavBar from "@/components/MobileNavBar";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}  ${inter.variable} h-full antialiased`}
    >
      <body className="bg-[#040807] font-inter">
        <div className='hidden md:block'>
          <NavBar />
        </div>
        <div className='block md:hidden'>
          <MobileNavBar />
        </div>
        <main>{children}</main>

      </body>
    </html>
  );
}
